name: Node.js Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '*/180 * * * *'

env:
  PROMETHEUS_URL: ${{ secrets.PROMETHEUS_URL }}
  LOKI_URL: ${{ secrets.LOKI_URL }}
  PROMETHEUS_USERNAME: ${{ secrets.PROMETHEUS_USERNAME }}
  LOKI_USERNAME: ${{ secrets.LOKI_USERNAME }}
  GRAFANA_CLOUD_ACCESS_TOKEN: ${{ secrets.GRAFANA_CLOUD_ACCESS_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}



jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Get changed files in the docs folder
      id: changed-files-specific
      uses: tj-actions/changed-files@v40
      with:
        files: node/**

    - name: Use Node.js ${{ matrix.node-version }}
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: NPM CI
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: npm ci

    - name: NPM build
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: npm run build --if-present
    
    - name: NPM Test
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: npm test
