name: PYPI Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release'
        required: true

permissions:
  contents: write

defaults:
  run:
    working-directory: ./python

jobs:
  publish:
    name: Publish Package to PYPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Create a new pyproject.toml
      run: |
        cat <<EOF > pyproject.toml
        [tool.poetry]
        name = "grafana-openai-monitoring"
        version = "${{ github.event.inputs.version }}"
        description = "Library to monitor your OpenAI usage and send metrics and logs to Grafana Cloud"
        authors = ["Ishan Jain <ishan.jain@grafana.com>"]
        repository = "https://github.com/grafana/grafana-openai-monitoring"
        readme = "README.md"
        homepage = "https://github.com/grafana/grafana-openai-monitoring"
        keywords = ["observability", "monitoring", "openai", "grafana", "gpt"]

        [tool.poetry.dependencies]
        python = "^3.7.1"
        requests = "^2.26.0"

        [build-system]
        requires = ["poetry-core>=1.1.0"]
        build-backend = "poetry.core.masonry.api"
        EOF

    - name: Build package
      run: python -m build
    
    - name: Publish Package
      run: python -m twine upload --repository pypi dist/*  --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [publish]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "python-${{ github.event.inputs.version }}"
